image: ruby:latest

cache:  # Add Bundler cache to 'vendor' directory
  paths:
    - vendor/

before_script:  # Install Gems to 'vendor' directory
  - bundle install --path vendor

test:
  stage: test
  script:  # Generate test site(s) into 'test' directory
  - bundle exec jekyll build -d test
  artifacts:  # Save a zipped version for download
    paths:
    - test
  except:  # Execute for all branches except main
  - main

pages:
  stage: deploy
  script:  # Generate public site and deploy
    - gem install jekyll
    - gem install jekyll-sitemap
    - jekyll build -d public --watch
  artifacts:  # Save a zipped version for download
    paths:
    - public
  only:  # Only deploy the main branch
  - main
